### ISSUE TITLE
Dell vostro 5471

### ISSUE THREAD

**Issue by Lyceris-chan** [tadghh/Dell-unlock-undervolting#1]
I tried this on my machine and the changes don't seem to stick i tried a different version of grub setup var as well and i tried the RU tool with no luck

**Comment by tadghh** [comment]
What command did you enter into grub, also wdym by the changes don't seem to stick? Also what are you using to see if voltage offsets are applying, throttlestop?

**Comment by Lyceris-chan** [comment]
I extracted the bios and obtained the required offsets and changed them to 0x00 using the grub thing and it didn't seem to stick after rebooting

**Comment by tadghh** [comment]
Can you give me more information than doesn't stick, what software are you using to change voltages in windows? Intel XTU is pretty iffy.

**Comment by Lyceris-chan** [comment]
I think it was the voltage control offset that didn't stick, and i use throttlestop. I am reinstalling windows right now to see if that helps and to free up some space

**Comment by tadghh** [comment]
Is secure boot enabled? I think it might need to be disabled I'm not to sure.

**Comment by Lyceris-chan** [comment]
i can send you a link to the bios i am on right now i think it could be a bios lock

**Comment by tadghh** [comment]
Well on your latest bios for that model 0x5D6 should be what you are setting to 0x00. Should be the same for previous versions.

**Comment by Lyceris-chan** [comment]
the 0x527 one is the one that doesn't stick then

**Comment by tadghh** [comment]
0x527  is the CFGLock not voltage lock. Change the one I mentioned to get voltage control on windows.

**Comment by Lyceris-chan** [comment]
I am not sure if the clean installed fixed it but it works now thanks for your work and your time and have a nice day! (also i didn't change the offset again after the reinstall)

**Comment by tadghh** [comment]
No problem!

**Comment by Lyceris-chan** [comment]
well its a year-ish later and I can now say it works properly using the following things:
(Values found on Windows, Laptop itself is running Arch Linux)

- Universal-IFR-Extractor: https://github.com/LongSoft/Universal-IFR-Extractor/releases/tag/v0.3.6
- BIOSUtilities: https://github.com/platomav/BIOSUtilities/releases/tag/DPUE-v5.1
- UEFITool: https://github.com/LongSoft/UEFITool/releases/tag/A59
- grub-mod-setup_var: https://github.com/datasone/grub-mod-setup_var/releases/tag/1.1

- Dell BIOS: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=8rjwr&oscode=wt64a&productcode=vostro-14-5471-laptop
