### ISSUE TITLE
Dell Precision 5520

### ISSUE THREAD

**Issue by dimasafonis** [tadghh/Dell-unlock-undervolting#4]
This guide works for this laptop on i7-7820HQ with offset 0x59C for Precision_5520_1.39.0.exe
The only problem is that it gets disabled again after exiting sleep mode or rebooting.

I've used `setup_var_3 0x59C 0x00` and then typed 'halt'. After booting I've applied undervolting values using intel-undervolt and it worked. But after exiting sleep mode, undervolting resets to 0 and I can't change it without going to grub shell again

**Comment by tadghh** [comment]
Do you witness the same behaviour on BIOS versions pre-2019? Is Intel XTU installed (although I doubt this would change it) amd just to sanity check which setup_var version did you use. Sometimes there are multiple locations for the same value (and setup_var_3 should cover all of them)

**Comment by dimasafonis** [comment]
I don't have Intel XTU installed
I've used 1.1 grub shell with setup_var_3, then halted. Applied undervolting, works. After rebooting and or sleep mode "Values do not equal". I even checked it twice
I'll test pre-2019 bios tomorrow

**Comment by tadghh** [comment]
Oh is there any chance the cmos battery has died? Can you save regular settings in the bios?

**Comment by dimasafonis** [comment]
The CMOS battery is okay and I've restored the default bios settings, didn't work. I've tried downgrading to 1.12.1, 1.11.0 and 1.10.1 but all of them failed with "Unable to load SMBIOS Table" error

**Comment by tadghh** [comment]
"But TIL that you can actually update the BIOS without Windows. Just put the update file on a FAT32-formatted USB drive, press F12 during boot (when the Dell logo is shown), select "BIOS Flash Update", browse to the update file, and that's it." [source](https://www.dell.com/community/en/conversations/precision-fixed-workstations/error-unable-to-load-the-smbios-table-bios-update-program-on-precision-5820-tower/647f826af4ccf8a8de1210e9?commentId=647f83f1f4ccf8a8de2c84d4)

try this?

**Comment by dimasafonis** [comment]
Downgrading to 1.12.1 bios fixes the problem, the offset is still 0x59C

**Comment by tadghh** [comment]
hurray! if everythings working now dont forget to close this issue

**Comment by dimasafonis** [comment]
Thanks for help! I guess I'll play a little with firmware files to check if there is anything that can make it work with the latest bios. Closing this issue now
